library(tidyverse)
library(ggsoccer)
library(StatsBombR)

### Preprocess the Data
## Retrieve all available competitions
Comp <- FreeCompetitions()

# Looking at the Bayern v. Dortmund UCL Final

## Filter Competition
ucl_england <- Comp |>
  filter(competition_id ==16 & season_name == "2004/2005")

# Retrieve all matches that correspond to that league and season
matches <- FreeMatches(ucl_england)

# Retrieve event data
events_df <- get.matchFree(matches)

# Clean data
clean_df <- allclean(events_df)

save(clean_df, file = 'ucl_0405.rda')

### Pass Map
# Pass maps show all passes created by a player or team.
# Filter data by taking all passes created by Gerrard
gerrard_pass <- clean_df |>
  filter(player.name == 'Steven Gerrard') |>
  filter(type.name == 'Pass')

# Create visualizations using ggplot and ggsoccer
ggplot(gerrard_pass) +
  annotate_pitch(dimensions = pitch_statsbomb) + 
  geom_segment(aes(x = location.x, y = location.y,
                   xend = pass.end_location.x, yend = pass.end_location.y),
               color = "coral",
               arrow = arrow(length = unit(0.15, "cm"),
                             type = "closed")) +
  labs(title = "Steven Gerrard's Passing Map",
       subtitle = "UCL Final 04/05",
       caption = "Source: StatsBomb") + theme_pitch()

# ggsoccer extends ggplot library, so we can build visualizations on event data that comprises the start and end coordinates.
# library provides annotate_pitch to create football pitch and geom_segment to create lines and passes

# Including some themes
ggplot(gerrard_pass) +
  annotate_pitch(dimensions = pitch_statsbomb, fill='#021e3f', colour='#DDDDDD') +
  geom_segment(aes(x=location.x, y=location.y, xend=pass.end_location.x, yend=pass.end_location.y),
               colour = "coral",
               arrow = arrow(length = unit(0.15, "cm"),
                             type = "closed")) + 
  labs(title="Steven Gerrard's Passing Map",
       subtitle="UEFA Champions League Final 04/05",
       caption="Data Source: StatsBomb") + 
  theme(
    plot.background = element_rect(fill='#021e3f', color='#021e3f'),
    panel.background = element_rect(fill='#021e3f', color='#021e3f'),
    plot.title = element_text(hjust=0.5, vjust=0, size=14),
    plot.subtitle = element_text(hjust=0.5, vjust=0, size=8),
    plot.caption = element_text(hjust=0.5),
    text = element_text(color='white'),
    panel.grid = element_blank(),
    axis.title = element_blank(),
    axis.text = element_blank()
  )

### Shots Map
# Creating a shot map for both teams, but we'll plot the shots generated by each club on different coordinates
# Creating 2 data frames of Bayern & Dortmund's shot data
milan_shot <- clean_df |>
  filter(type.name == 'Shot') |>
  filter(team.name == 'AC Milan') |>
  select(player.name, location.x, location.y, shot.end_location.x,
         shot.end_location.y, shot.statsbomb_xg)
liverpool_shot <- clean_df |>
  filter(type.name == 'Shot') %>%
  filter(team.name == 'Liverpool') %>%
  select(player.name, location.x, location.y, shot.end_location.x, shot.end_location.y, shot.statsbomb_xg)
# change geom_segment function with geom_point function
# apply function to each data frame. For Dortmund's shot data, we reflect the x-coordinates by subtracting the value by 120

ggplot() +
  annotate_pitch(dimensions = pitch_statsbomb, colour = "white",
                 fill = "#021e3f") +
  geom_point(data = liverpool_shot, aes(x = location.x, y = location.y,
                                       size = shot.statsbomb_xg), color = "red4") +
  geom_point(data = milan_shot, aes(x = 120-location.x, y = location.y,
                                     size = shot.statsbomb_xg), color = "white") +
  labs(
    title = "AC Milan vs. Liverppol",
    subtitle = "Shots Map | UEFA Champions League Final 2004/2005",
    caption = "Source: StatsBomb") + 
  theme(
    plot.background = element_rect(fill='#021e3f', color='#021e3f'),
    panel.background = element_rect(fill='#021e3f', color='#021e3f'),
    plot.title = element_text(hjust=0.5, vjust=0, size=14),
    plot.subtitle = element_text(hjust=0.5, vjust=0, size=8),
    plot.caption = element_text(hjust=0.5),
    text = element_text(color='white'),
    panel.grid = element_blank(),
    axis.title = element_blank(),
    axis.text = element_blank(),
    legend.position = 'none'
  )


### Pressures Heat Map
liverpool_pressure <- clean_df |>
  filter(team.name == 'Liverpool') |>
  filter(type.name == 'Pressure')

ggplot(liverpool_pressure) +
  annotate_pitch(dimensions = pitch_statsbomb, fill='#021e3f', colour='#DDDDDD') +
  geom_point(aes(location.x, location.y)) + 
  geom_density2d_filled(aes(location.x, location.y, fill=..level..), alpha=0.4, contour_var='ndensity') +
  scale_x_continuous(c(0, 120)) +
  scale_y_continuous(c(0, 80)) +
  labs(title="Liverpool's Pressure Heat Map",
       subtitle="UEFA Champions League Final 04/05",
       caption="Data Source: StatsBomb") + 
  theme_minimal() +
  theme(
    plot.background = element_rect(fill='#021e3f', color='#021e3f'),
    panel.background = element_rect(fill='#021e3f', color='#021e3f'),
    plot.title = element_text(hjust=0.5, vjust=0, size=14),
    plot.subtitle = element_text(hjust=0.5, vjust=0, size=8),
    plot.caption = element_text(hjust=0.5),
    text = element_text(color='white'),
    panel.grid = element_blank(),
    axis.title = element_blank(),
    axis.text = element_blank(),
    legend.position = "none"
  )
# change geom_point function with geom_density2d_filled to generate heat map. Also add scale function to specify heat map range.